import SwiftUI
import SwiftData

// MARK: - PDF Portfolio View
// Student portfolio preview and text export

struct PDFPortfolioView: View {
    @Environment(\.dismiss) private var dismiss
    @Query private var students: [StudentProfileModel]
    @Query private var activities: [ActivityModel]
    @Query private var applications: [ApplicationModel]
    @State private var showShareSheet = false

    private var student: StudentProfileModel? { students.first }

    private var portfolioText: String {
        var lines: [String] = []
        lines.append("STUDENT PORTFOLIO")
        lines.append("=================")
        lines.append("")

        if let s = student {
            lines.append("Name: \(s.fullName)")
            lines.append("Grade: \(s.grade)")
            if let school = s.schoolName { lines.append("School: \(school)") }
            lines.append("")

            // Academics
            lines.append("ACADEMICS")
            lines.append("---------")
            if let gpa = s.gpa { lines.append("GPA: \(String(format: "%.2f", gpa))") }
            if let sat = s.satScore { lines.append("SAT: \(sat)") }
            if let act = s.actScore { lines.append("ACT: \(act)") }
            if !s.apCourses.isEmpty { lines.append("AP Courses: \(s.apCourses.joined(separator: ", "))") }
            lines.append("")
        }

        // Activities
        if !activities.isEmpty {
            lines.append("ACTIVITIES")
            lines.append("----------")
            for (i, activity) in activities.enumerated() {
                var line = "\(i + 1). \(activity.name) (\(activity.category))"
                if let role = activity.role { line += " - \(role)" }
                lines.append(line)
                if let impact = activity.impactStatement { lines.append("   \(impact)") }
            }
            lines.append("")
        }

        // College list
        if !applications.isEmpty {
            lines.append("COLLEGE LIST")
            lines.append("------------")
            for app in applications {
                var line = "- \(app.collegeName)"
                line += " [\(app.status.capitalized)]"
                if let type = app.deadlineType { line += " (\(type))" }
                lines.append(line)
            }
            lines.append("")
        }

        // Honors
        let awards = activities.filter { $0.category == "Award" }
        if !awards.isEmpty {
            lines.append("HONORS & AWARDS")
            lines.append("---------------")
            for award in awards {
                lines.append("- \(award.name)")
            }
            lines.append("")
        }

        lines.append("Generated by Ladder")
        return lines.joined(separator: "\n")
    }

    var body: some View {
        ZStack {
            LadderColors.surface.ignoresSafeArea()

            ScrollView(showsIndicators: false) {
                VStack(spacing: LadderSpacing.xl) {
                    // Header
                    VStack(alignment: .leading, spacing: LadderSpacing.sm) {
                        Text("Student Portfolio")
                            .font(LadderTypography.headlineMedium)
                            .foregroundStyle(LadderColors.onSurface)

                        Text("Preview and share your college prep summary")
                            .font(LadderTypography.bodyMedium)
                            .foregroundStyle(LadderColors.onSurfaceVariant)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(.top, LadderSpacing.lg)

                    // Student header card
                    if let student = student {
                        HStack(spacing: LadderSpacing.md) {
                            Circle()
                                .fill(LadderColors.primaryContainer)
                                .frame(width: 48, height: 48)
                                .overlay {
                                    Text(String(student.firstName.prefix(1)))
                                        .font(LadderTypography.titleMedium)
                                        .foregroundStyle(.white)
                                }

                            VStack(alignment: .leading, spacing: 2) {
                                Text(student.fullName)
                                    .font(LadderTypography.titleMedium)
                                    .foregroundStyle(LadderColors.onSurface)
                                Text("Grade \(student.grade)")
                                    .font(LadderTypography.bodySmall)
                                    .foregroundStyle(LadderColors.onSurfaceVariant)
                            }

                            Spacer()

                            VStack(alignment: .trailing, spacing: 2) {
                                if let gpa = student.gpa {
                                    Text("GPA \(String(format: "%.2f", gpa))")
                                        .font(LadderTypography.titleSmall)
                                        .foregroundStyle(LadderColors.primary)
                                }
                                if let sat = student.satScore {
                                    Text("SAT \(sat)")
                                        .font(LadderTypography.bodySmall)
                                        .foregroundStyle(LadderColors.onSurfaceVariant)
                                }
                            }
                        }
                        .padding(LadderSpacing.lg)
                        .background(LadderColors.surfaceContainerLow)
                        .clipShape(RoundedRectangle(cornerRadius: LadderRadius.xl, style: .continuous))
                    }

                    // Activities section
                    if !activities.isEmpty {
                        portfolioSection(title: "Activities", icon: "person.3.fill") {
                            ForEach(activities) { activity in
                                HStack(spacing: LadderSpacing.sm) {
                                    Image(systemName: ActivityModel.categoryIcons[activity.category] ?? "circle")
                                        .font(.system(size: 14))
                                        .foregroundStyle(LadderColors.primary)
                                        .frame(width: 24)

                                    VStack(alignment: .leading, spacing: 2) {
                                        Text(activity.name)
                                            .font(LadderTypography.bodyMedium)
                                            .foregroundStyle(LadderColors.onSurface)
                                        if let role = activity.role {
                                            Text(role)
                                                .font(LadderTypography.labelSmall)
                                                .foregroundStyle(LadderColors.onSurfaceVariant)
                                        }
                                    }

                                    Spacer()

                                    Text(activity.category)
                                        .font(LadderTypography.labelSmall)
                                        .foregroundStyle(LadderColors.onSurfaceVariant)
                                        .padding(.horizontal, LadderSpacing.sm)
                                        .padding(.vertical, LadderSpacing.xxs)
                                        .background(LadderColors.surfaceContainerHighest)
                                        .clipShape(Capsule())
                                }
                            }
                        }
                    }

                    // College list section
                    if !applications.isEmpty {
                        portfolioSection(title: "College List", icon: "building.columns") {
                            ForEach(applications) { app in
                                HStack {
                                    Text(app.collegeName)
                                        .font(LadderTypography.bodyMedium)
                                        .foregroundStyle(LadderColors.onSurface)
                                    Spacer()
                                    Text(app.status.capitalized)
                                        .font(LadderTypography.labelSmall)
                                        .foregroundStyle(app.status == "accepted" || app.status == "committed" ? LadderColors.primary : LadderColors.onSurfaceVariant)
                                }
                            }
                        }
                    }

                    // Awards section
                    let awards = activities.filter { $0.category == "Award" }
                    if !awards.isEmpty {
                        portfolioSection(title: "Honors & Awards", icon: "trophy.fill") {
                            ForEach(awards) { award in
                                HStack {
                                    Text(award.name)
                                        .font(LadderTypography.bodyMedium)
                                        .foregroundStyle(LadderColors.onSurface)
                                    Spacer()
                                    if let impact = award.impactStatement {
                                        Text(impact)
                                            .font(LadderTypography.labelSmall)
                                            .foregroundStyle(LadderColors.onSurfaceVariant)
                                            .lineLimit(1)
                                    }
                                }
                            }
                        }
                    }

                    // Action buttons
                    VStack(spacing: LadderSpacing.md) {
                        LadderPrimaryButton("Share Portfolio", icon: "square.and.arrow.up") {
                            showShareSheet = true
                        }
                    }

                    Spacer().frame(height: 100)
                }
                .padding(.horizontal, LadderSpacing.lg)
            }
        }
        .navigationBarBackButtonHidden(true)
        .toolbar {
            ToolbarItem(placement: .navigationBarLeading) {
                Button { dismiss() } label: {
                    Image(systemName: "chevron.left")
                        .font(.system(size: 16, weight: .semibold))
                        .foregroundStyle(LadderColors.onSurface)
                }
            }
            ToolbarItem(placement: .principal) {
                Text("Portfolio")
                    .font(LadderTypography.titleSmall)
                    .foregroundStyle(LadderColors.onSurface)
            }
        }
        .sheet(isPresented: $showShareSheet) {
            ShareSheet(items: [portfolioText])
        }
    }

    // MARK: - Portfolio Section

    private func portfolioSection<Content: View>(title: String, icon: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: LadderSpacing.md) {
            HStack(spacing: LadderSpacing.sm) {
                Image(systemName: icon)
                    .font(.system(size: 14))
                    .foregroundStyle(LadderColors.primary)
                Text(title)
                    .font(LadderTypography.titleSmall)
                    .foregroundStyle(LadderColors.onSurface)
            }

            content()
        }
        .padding(LadderSpacing.lg)
        .background(LadderColors.surfaceContainerLow)
        .clipShape(RoundedRectangle(cornerRadius: LadderRadius.xl, style: .continuous))
    }
}
