-- 0008 — Default app_metadata stamp for B2C direct-signup users.
-- STATUS: NO-OP (intentionally empty). See note below.
--
-- ORIGINAL INTENT
-- The iOS app reads role + tenant_id from JWT app_metadata claims. Without
-- a stamp in raw_app_meta_data, every Release-build sign-in throws
-- LadderAuthError.missingRoleClaim for users who did NOT redeem an invite.
-- The original plan was a Postgres trigger on auth.users AFTER INSERT that
-- stamped raw_app_meta_data = { "role": "student", "tenant_id": null }
-- when role was absent.
--
-- WHY THIS MIGRATION IS A NO-OP
-- Supabase Hosted does not allow regular project roles to attach triggers
-- to tables in the `auth` schema or create functions there:
--   ERROR: permission denied for schema auth (SQLSTATE 42501)
-- This is a platform-wide reserved-schema policy.
--
-- THE ACTUAL FIX (Phase 4 backlog)
-- Two Supabase-idiomatic paths exist; pick one in Phase 4:
--   (a) Auth Hook `custom-access-token`: configure in Supabase dashboard
--       (Auth → Hooks). Point at a public-schema function that returns
--       the role + tenant_id claims every time the JWT is minted. Pros:
--       no client-side change, no race; Cons: dashboard config required,
--       function lives in public.
--   (b) Edge Function `bootstrap-user`: iOS calls this immediately after
--       successful signUp(). The function uses service_role to stamp
--       app_metadata. iOS then refreshes the JWT. Pros: pure code, no
--       dashboard config; Cons: extra round-trip on first sign-in, more
--       iOS code.
--
-- INTERIM BEHAVIOR (until Phase 4 ships one of the above)
--   - School-tenant signups (invite-redeem path): WORK CORRECTLY. The
--     invite-redeem Edge Function already calls auth.admin.updateUserById
--     with role + tenant_id from the invite. See
--     supabase/functions/invite-redeem/index.ts (this commit).
--   - B2C direct signups (no invite): produce a claim-less JWT. The iOS
--     SupabaseAuthService throws LadderAuthError.missingRoleClaim in
--     Release. In DEBUG it logs and falls back to .student. So B2C
--     direct sign-up is BLOCKED in Release builds until Phase 4.
--   - Founder login: separate path (founder_users table); not affected.
--
-- DO NOT add SQL below this line. Add it in a NEW migration that does
-- the right thing via Auth Hook or by creating the bootstrap Edge
-- Function (no migration needed for that path).

select 1;  -- Placeholder so the migration file isn't empty. NO side effects.
