#!/usr/bin/env bash
# scripts/secrets-sync.sh — reads .env (gitignored) and writes:
#   Config/Secrets.xcconfig  (iOS public anon keys)
#   Supabase CLI secrets     (server-side keys for Edge Functions)
#
# Never logs secret values. Missing keys fail loud.

set -euo pipefail

ENV_FILE=".env"
if [ ! -f "$ENV_FILE" ]; then
  echo "ERROR: $ENV_FILE not found. Copy .env.example to .env and fill in."
  exit 1
fi
# shellcheck disable=SC1090
source "$ENV_FILE"

required_public=(SUPABASE_URL SUPABASE_ANON_KEY GEMINI_PROXY_URL)
for k in "${required_public[@]}"; do
  if [ -z "${!k:-}" ]; then
    echo "ERROR: $k missing in .env"
    exit 1
  fi
done

mkdir -p Config
cat > Config/Secrets.xcconfig <<EOF
// Auto-generated by scripts/secrets-sync.sh. DO NOT COMMIT.
SUPABASE_URL      = $SUPABASE_URL
SUPABASE_ANON_KEY = $SUPABASE_ANON_KEY
GEMINI_PROXY_URL  = $GEMINI_PROXY_URL
EOF

# Push server-side secrets to Supabase (requires supabase CLI + project link).
if command -v supabase >/dev/null; then
  supabase secrets set \
    SUPABASE_SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY:-}" \
    GEMINI_API_KEY="${GEMINI_API_KEY:-}" \
    GEMINI_MODEL="${GEMINI_MODEL:-gemini-1.5-pro}" \
    AWS_REGION="${AWS_REGION:-us-east-1}" \
    LADDER_KMS_CMK_ID="${LADDER_KMS_CMK_ID:-}" \
    AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-}" \
    AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-}" \
    >/dev/null
  echo "Supabase secrets updated."
else
  echo "supabase CLI not found — server-side secrets NOT pushed. Install via 'make bootstrap'."
fi

echo "secrets-sync: done."
